version: '3'
services:
  victim:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: victim_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_DEBUG=1
    networks:
      - victim_network

networks:
  victim_network:
    driver: bridge